# Generated by Django 5.0.1 on 2024-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_parking_start_reservation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="start_reservation",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="parking",
            name="stop_reservation",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="parking",
            name="user_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
