# Generated by Django 5.0.1 on 2024-02-07 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_parking_start_reservation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parking",
            old_name="parking_lot_id",
            new_name="parking_lot",
        ),
    ]
