# Generated by Django 5.0.1 on 2024-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_rename_parking_lot_id_parking_parking_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="parking_lot_id",
            field=models.IntegerField(default=0),
        ),
    ]
